
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jul 16 11:16:04 IRKST 2011
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FLOATVALUE = 5;
  public static final int AS = 11;
  public static final int TIMES = 56;
  public static final int FROM = 21;
  public static final int GT = 61;
  public static final int GROUP = 74;
  public static final int TABLE = 35;
  public static final int GE = 63;
  public static final int ASC = 12;
  public static final int NAME = 2;
  public static final int LIKE = 26;
  public static final int COMMA = 69;
  public static final int SUM = 44;
  public static final int RPAREN = 51;
  public static final int ALL = 8;
  public static final int LT = 60;
  public static final int INCREMENT = 72;
  public static final int INTVALUE = 4;
  public static final int LPAREN = 50;
  public static final int FALSE = 49;
  public static final int NOT = 27;
  public static final int LE = 62;
  public static final int VIEW = 37;
  public static final int FLOAT = 46;
  public static final int MIN = 42;
  public static final int EQ = 64;
  public static final int MOD = 59;
  public static final int INTO = 24;
  public static final int SELECT = 34;
  public static final int TRUE = 48;
  public static final int ALTER = 6;
  public static final int PLUS = 55;
  public static final int DIVIDE = 58;
  public static final int INDEX = 22;
  public static final int EXISTS = 20;
  public static final int ORDER = 31;
  public static final int UNION = 66;
  public static final int USE = 68;
  public static final int DELETE = 15;
  public static final int CHAR = 71;
  public static final int BOOLEAN = 47;
  public static final int ESCAPE = 19;
  public static final int ADD = 7;
  public static final int MAX = 43;
  public static final int DOT = 54;
  public static final int INT = 45;
  public static final int AVG = 40;
  public static final int NULL = 28;
  public static final int EOF = 0;
  public static final int SEMICOLON = 67;
  public static final int WHERE = 39;
  public static final int DEFAULT = 70;
  public static final int COUNT = 41;
  public static final int MINUS = 57;
  public static final int IN = 76;
  public static final int OR = 30;
  public static final int SET = 33;
  public static final int error = 1;
  public static final int ON = 29;
  public static final int DESC = 16;
  public static final int DATABASE = 18;
  public static final int CHECK = 53;
  public static final int BY = 13;
  public static final int VALUES = 38;
  public static final int ANY = 10;
  public static final int CREATE = 14;
  public static final int UPDATE = 36;
  public static final int INSERT = 23;
  public static final int STRING = 3;
  public static final int NEQ = 65;
  public static final int PRIMARY = 32;
  public static final int AND = 9;
  public static final int DROP = 17;
  public static final int KEY = 25;
  public static final int HAVING = 75;
  public static final int DISTINCT = 73;
  public static final int AUTO = 52;
  public static final int ERROR=110; 
}

