
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jul 12 22:41:13 IRKST 2011
//----------------------------------------------------

package Parse;

import java_cup.runtime.Symbol;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FLOATVALUE = 54;
  public static final int AS = 7;
  public static final int TIMES = 57;
  public static final int FROM = 17;
  public static final int GT = 62;
  public static final int GROUP = 75;
  public static final int TABLE = 31;
  public static final int GE = 64;
  public static final int ASC = 8;
  public static final int NAME = 47;
  public static final int LIKE = 22;
  public static final int COMMA = 70;
  public static final int SUM = 40;
  public static final int RPAREN = 49;
  public static final int ALL = 4;
  public static final int LT = 61;
  public static final int INCREMENT = 73;
  public static final int INTVALUE = 53;
  public static final int LPAREN = 48;
  public static final int FALSE = 46;
  public static final int NOT = 23;
  public static final int LE = 63;
  public static final int VIEW = 33;
  public static final int FLOAT = 43;
  public static final int MIN = 38;
  public static final int EQ = 65;
  public static final int MOD = 60;
  public static final int INTO = 20;
  public static final int SELECT = 30;
  public static final int TRUE = 45;
  public static final int ALTER = 2;
  public static final int PLUS = 56;
  public static final int DIVIDE = 59;
  public static final int INDEX = 18;
  public static final int EXISTS = 16;
  public static final int ORDER = 27;
  public static final int UNION = 67;
  public static final int USE = 69;
  public static final int DELETE = 11;
  public static final int CHAR = 72;
  public static final int BOOLEAN = 44;
  public static final int ESCAPE = 15;
  public static final int ADD = 3;
  public static final int MAX = 39;
  public static final int DOT = 52;
  public static final int INT = 41;
  public static final int AVG = 36;
  public static final int NULL = 24;
  public static final int EOF = 0;
  public static final int SEMICOLON = 68;
  public static final int WHERE = 35;
  public static final int DEFAULT = 71;
  public static final int COUNT = 37;
  public static final int MINUS = 58;
  public static final int IN = 77;
  public static final int OR = 26;
  public static final int SET = 29;
  public static final int error = 1;
  public static final int ON = 25;
  public static final int DESC = 12;
  public static final int STRINGVALUE = 55;
  public static final int DATABASE = 14;
  public static final int CHECK = 51;
  public static final int BY = 9;
  public static final int VALUES = 34;
  public static final int ANY = 6;
  public static final int CREATE = 10;
  public static final int UPDATE = 32;
  public static final int INSERT = 19;
  public static final int STRING = 42;
  public static final int NEQ = 66;
  public static final int PRIMARY = 28;
  public static final int AND = 5;
  public static final int DROP = 13;
  public static final int KEY = 21;
  public static final int HAVING = 76;
  public static final int DISTINCT = 74;
  public static final int AUTO = 50; 
  public static final int ERROR = 100; 
}

